[2024-04-18 20:35:13,359] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:13] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:16,430] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:16] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:16,435] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:16] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:43,510] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:43] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:36:12,475] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:36:12] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:36:13,992] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:36:13] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:36:46,756] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:36:46] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:37:22,089] ERROR log_exception() L838  Exception on /reserva [DELETE] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 123, in del_reserva
    reserva_dataReserva = unquote(unquote(query.dataReserva))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 684, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'datetime.date' is not iterable
[2024-04-18 20:37:22,097] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:37:22] "[35m[1mDELETE /reserva?dataReserva=2024-04-30 HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:40:15,800] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:40:15] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:40:24,717] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:40:24] "OPTIONS /reserva?nome=111111111111 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:40:24,720] ERROR log_exception() L838  Exception on /reserva [DELETE] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 123, in del_reserva
    reserva_dataReserva = unquote(unquote(query.dataReserva))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 684, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'datetime.date' is not iterable
[2024-04-18 20:40:24,727] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:40:24] "[35m[1mDELETE /reserva?nome=111111111111 HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:04:33,102] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:04:33] "OPTIONS /reserva?nome=222222222222 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:04:33,105] ERROR log_exception() L838  Exception on /reserva [DELETE] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 123, in del_reserva
    reserva_dataReserva = unquote(unquote(query.dataReserva))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 684, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'datetime.date' is not iterable
[2024-04-18 21:04:33,111] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:04:33] "[35m[1mDELETE /reserva?nome=222222222222 HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:05:04,942] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:05:04,943] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:05:04] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
