[2024-04-18 20:23:46,366] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:23:46] "[35m[1mDELETE /reserva?nome=Teste HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:23:54,401] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:23:54] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:23:54,409] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:23:54] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:24:01,341] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:24:01] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:24:47,270] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 20:24:47,271] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:24:47] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:02,490] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:02] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:12,217] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:12] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:17,128] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:17] "OPTIONS /reserva?nome=111111111111 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:17,131] ERROR log_exception() L838  Exception on /reserva [DELETE] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 123, in del_reserva
    reserva_dataReserva = unquote(unquote(query.dataReserva))
                                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 792, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ReservaBuscaSchema' object has no attribute 'dataReserva'
[2024-04-18 20:26:17,138] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:17] "[35m[1mDELETE /reserva?nome=111111111111 HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:21,014] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:21] "OPTIONS /reserva?nome=111111111111 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:26:21,018] ERROR log_exception() L838  Exception on /reserva [DELETE] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 123, in del_reserva
    reserva_dataReserva = unquote(unquote(query.dataReserva))
                                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 792, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ReservaBuscaSchema' object has no attribute 'dataReserva'
[2024-04-18 20:26:21,025] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:26:21] "[35m[1mDELETE /reserva?nome=111111111111 HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:34:59,084] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.116:5000 - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:34:59,086] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,731] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,830] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,831] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,832] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,940] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,990] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:06,992] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:06] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:35:13,354] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:35:13] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
