[2024-04-18 21:49:45,816] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:45] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:45,824] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:45] "[36mGET /openapi/static/images/apidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:46,740] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:46] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:46,771] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:46] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:46,773] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:46] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:46,776] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:46] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:47,006] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:47] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:47,040] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:47] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:52,285] WARNING add_reserva() L64   Erro ao adicionar a reserva '2024-04-30', Não foi possível salvar novo item :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L64  
[2024-04-18 21:49:52,285] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:52] "[31m[1mPOST /reserva HTTP/1.1[0m" 400 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:49:55,137] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:49:55,138] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:49:55] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:50:19,082] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:50:19,083] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:50:19] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:50:41,722] WARNING add_reserva() L64   Erro ao adicionar a reserva '2024-04-29', Não foi possível salvar novo item :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L64  
[2024-04-18 21:50:41,723] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:50:41] "[31m[1mPOST /reserva HTTP/1.1[0m" 400 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:52:13,431] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:52:13,432] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:52:13] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:52:38,367] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:52:38,368] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:52:38] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:53:26,086] WARNING add_reserva() L64   Erro ao adicionar a reserva '2024-05-01', Não foi possível salvar novo item :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L64  
[2024-04-18 21:53:26,087] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:53:26] "[31m[1mPOST /reserva HTTP/1.1[0m" 400 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:53:57,060] ERROR log_exception() L838  Exception on /reservas [GET] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 88, in get_reservas
    return apresenta_reservas(reservas), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\schemas\reserva.py", line 42, in apresenta_reservas
    "dataReserva": reserva.dataReserva,
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Reserva' object has no attribute 'dataReserva'. Did you mean: 'dataReserva_str'?
[2024-04-18 21:53:57,067] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:53:57] "[35m[1mGET /reservas HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:25,749] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.116:5000 - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:25,750] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:29,191] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:29] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:46,630] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:46,642] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:46,721] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:46,728] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:46,783] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
