[2024-04-17 23:31:32,366] ERROR log_exception() L838  Exception on /reservas [GET] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 88, in get_reservas
    return apresenta_reservas(reservas), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\schemas\reserva.py", line 75, in apresenta_reservas
    "id": reserva.id,
          ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'id'
[2024-04-17 23:31:32,379] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 23:31:32] "[35m[1mGET /reservas HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:30,628] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.116:5000 - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:30,629] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:33,961] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:33] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:33,978] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:33] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:34,094] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:34] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:34,096] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:34] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:34,160] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:34] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:34,171] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:34] "[36mGET /openapi/static/images/apidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,307] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,412] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,479] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,551] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,756] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:35,789] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:35] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 20:22:40,960] ERROR log_exception() L838  Exception on /reserva [GET] - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py", line 98, in get_reserva
    reserva_id = query.id
                 ^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 792, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ReservaBuscaSchema' object has no attribute 'id'
[2024-04-18 20:22:40,982] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 20:22:40] "[35m[1mGET /reserva?nome=Teste HTTP/1.1[0m" 500 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
